-- Migration: 012_de_multistep_workflow.sql
-- Description: Add multi-step workflow support for Designated Examiner
-- Created: 2025-12-04
--
-- This migration transforms the DE feature from a single-step transcript-based workflow
-- to a 5-step workflow that:
--   1. Accepts Epic documentation (CDE, Progress Notes, Ad-hoc Notes)
--   2. AI analyzes against Utah's 5 criteria and generates clarifying questions
--   3. User records patient interview responses
--   4. AI generates final determination
--   5. Displays court-ready testimony

-- ============================================================================
-- STEP 1: Add documentation input fields (replacing single transcript approach)
-- ============================================================================

-- CDE (Comprehensive Psychiatric Evaluation) - Required input
-- This is the Epic intake note for inpatient psychiatry at HMHI
ALTER TABLE designated_examiner_reports
  ADD COLUMN IF NOT EXISTS cde_note TEXT;

-- Progress Notes - Optional but encouraged
-- Daily notes that a physician writes about patient progress
ALTER TABLE designated_examiner_reports
  ADD COLUMN IF NOT EXISTS progress_notes TEXT;

-- Ad-hoc Notes - Optional
-- Informal notes from conversations with staff/nursing, attending, collateral
ALTER TABLE designated_examiner_reports
  ADD COLUMN IF NOT EXISTS adhoc_notes TEXT;

-- Patient name - Required (was previously optional)
ALTER TABLE designated_examiner_reports
  ADD COLUMN IF NOT EXISTS patient_name VARCHAR(255);

-- ============================================================================
-- STEP 2: Add workflow tracking columns
-- ============================================================================

-- Current step in the workflow (1-5)
-- 1 = Documentation Input
-- 2 = AI Analysis (first Gemini call)
-- 3 = Interview Questions (user inputs patient responses)
-- 4 = Final Determination (second Gemini call)
-- 5 = Testimony View (complete)
ALTER TABLE designated_examiner_reports
  ADD COLUMN IF NOT EXISTS workflow_step INTEGER DEFAULT 1;

-- Workflow status for filtering and management
ALTER TABLE designated_examiner_reports
  ADD COLUMN IF NOT EXISTS workflow_status VARCHAR(20) DEFAULT 'in_progress';

-- Add check constraint for workflow_status
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint WHERE conname = 'de_workflow_status_check'
  ) THEN
    ALTER TABLE designated_examiner_reports
      ADD CONSTRAINT de_workflow_status_check
      CHECK (workflow_status IN ('in_progress', 'completed', 'abandoned'));
  END IF;
END $$;

-- ============================================================================
-- STEP 3: Add AI analysis output columns (Step 2 results)
-- ============================================================================

-- Initial analysis from first Gemini call
-- JSON structure:
-- {
--   "criteria": {
--     "criterion_1": { "status": "meets|does_not_meet|unclear", "explanation": "...", "sources": ["CDE"] },
--     "criterion_2": { ... },
--     ...
--   },
--   "preliminary_recommendation": "...",
--   "generated_at": "2025-12-04T..."
-- }
ALTER TABLE designated_examiner_reports
  ADD COLUMN IF NOT EXISTS initial_analysis JSONB;

-- Clarifying questions generated by AI
-- JSON array structure:
-- [
--   { "id": "q1", "criterion": 2, "question": "...", "context": "...", "priority": "high|medium|low" },
--   ...
-- ]
ALTER TABLE designated_examiner_reports
  ADD COLUMN IF NOT EXISTS clarifying_questions JSONB;

-- ============================================================================
-- STEP 4: Add interview answers column (Step 3 results)
-- ============================================================================

-- User-recorded answers from patient interview
-- JSON object structure:
-- {
--   "q1": "Patient stated...",
--   "q2": "Patient denied...",
--   ...
-- }
ALTER TABLE designated_examiner_reports
  ADD COLUMN IF NOT EXISTS interview_answers JSONB;

-- ============================================================================
-- STEP 5: Add final determination columns (Step 4 results)
-- ============================================================================

-- Final analysis from second Gemini call
-- JSON structure:
-- {
--   "criteria": {
--     "criterion_1": { "status": "meets|does_not_meet", "explanation": "...", "sources": [...] },
--     ...
--   },
--   "overall_recommendation": "commit|do_not_commit",
--   "commitment_length": "30-day|60-day|90-day|null",
--   "reasoning": "Full legal reasoning...",
--   "generated_at": "2025-12-04T..."
-- }
ALTER TABLE designated_examiner_reports
  ADD COLUMN IF NOT EXISTS final_analysis JSONB;

-- Court-ready recommendation text (Step 5 display)
-- This is the text that can be read verbatim to the judge
ALTER TABLE designated_examiner_reports
  ADD COLUMN IF NOT EXISTS final_recommendation TEXT;

-- ============================================================================
-- STEP 6: Add indexes for workflow queries
-- ============================================================================

-- Index for listing in-progress reports by user
CREATE INDEX IF NOT EXISTS idx_de_reports_workflow
  ON designated_examiner_reports (finalized_by, workflow_status, workflow_step);

-- Index for filtering by workflow status
CREATE INDEX IF NOT EXISTS idx_de_reports_status
  ON designated_examiner_reports (workflow_status);

-- ============================================================================
-- STEP 7: Add column comments for documentation
-- ============================================================================

COMMENT ON COLUMN designated_examiner_reports.cde_note IS 'Comprehensive Psychiatric Evaluation - Epic intake note for inpatient psych (required)';
COMMENT ON COLUMN designated_examiner_reports.progress_notes IS 'Daily physician progress notes from Epic (optional but encouraged)';
COMMENT ON COLUMN designated_examiner_reports.adhoc_notes IS 'Informal notes from staff/nursing/attending/collateral conversations (optional)';
COMMENT ON COLUMN designated_examiner_reports.patient_name IS 'Patient name identifier (required)';
COMMENT ON COLUMN designated_examiner_reports.workflow_step IS 'Current workflow step: 1=Input, 2=Analysis, 3=Interview, 4=Determination, 5=Testimony';
COMMENT ON COLUMN designated_examiner_reports.workflow_status IS 'Workflow status: in_progress, completed, abandoned';
COMMENT ON COLUMN designated_examiner_reports.initial_analysis IS 'JSON output from first Gemini call - criteria assessment and preliminary recommendation';
COMMENT ON COLUMN designated_examiner_reports.clarifying_questions IS 'JSON array of AI-generated questions for ambiguous/unmet criteria';
COMMENT ON COLUMN designated_examiner_reports.interview_answers IS 'JSON object of user-recorded patient answers keyed by question ID';
COMMENT ON COLUMN designated_examiner_reports.final_analysis IS 'JSON output from second Gemini call - final criteria assessment';
COMMENT ON COLUMN designated_examiner_reports.final_recommendation IS 'Court-ready recommendation text for judge testimony';
